const DEFAULT_MAX_STORAGE_BUFFER_BINDING_SIZE = 128 * 1024 * 1024; // 128 MB
const DEFAULT_VERTEX_CAPACITY = 1 << 22; // 4M
const DEFAULT_TRIANGLE_CAPACITY = 1 << 20; // 1M
const DEFAULT_MESH_CAPACITY = 300;
const DEFAULT_MATERIAL_CAPACITY = 100;

export {
  DEFAULT_MAX_STORAGE_BUFFER_BINDING_SIZE,
  DEFAULT_VERTEX_CAPACITY,
  DEFAULT_TRIANGLE_CAPACITY,
  DEFAULT_MESH_CAPACITY,
  DEFAULT_MATERIAL_CAPACITY,
};
